#端口配置
server:
  port: 28090
  servlet:
    context-path: /myshopping
    session:
      timeout: 3600s
    jsp:
      init-parameters:
        development: true

spring:
  application:
    name: myshopping
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  #整合jsp
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
  #文件上传
  servlet: 
    multipart: 
      max-file-size: 5MB
   
# MyBatis
mybatis:
  type-aliases-package: com.mutil.userful.domain
  mapperLocations: classpath:mapper/*.xml


# 分布式文件系统FDFS配置
fdfs:
  soTimeout: 1500 #socket连接超时时长
  connectTimeout: 600 #连接tracker服务器超时时长
  reqHost: 192.168.140.130    #nginx访问地址
  reqPort: 8888               #nginx访问端口
  thumbImage: #缩略图生成参数，可选
      width: 150
      height: 150
  trackerList: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
      - 192.168.140.134:22122