#端口配置
server:
  port: 28090
  servlet:
    context-path: /userful
    session:
      timeout: 3600s
    jsp:
      init-parameters:
        development: true

spring:
  application:
    name: userful
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  #整合jsp
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
  #文件上传
  servlet: 
    multipart: 
      max-file-size: 5MB
  cloud: 
    consul: 
      discovery:
        enable: true
        instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress:${random.value}}
        serviceName: ${spring.application.name}
        preferIpAddress: true
        port: 28090
        healthCheckPath: ${server.context-path}/health
        tags:
   
# MyBatis
mybatis:
  type-aliases-package: com.mutil.userful.domain
  mapperLocations: classpath:mapper/*.xml